'use client'

import { useState } from 'react'
import { usePathname } from 'next/navigation'
import {
  Menu,
  MenuButton,
  MenuItem,
  MenuItems,
} from '@headlessui/react'
import clsx from 'clsx'

type Status = 'idle' | 'copying' | 'copied' | 'error'

/**
 * Map the current pathname to the matching .md mirror generated by
 * scripts/generate-llms.mjs.
 *   /                  -> /index.md
 *   /v7/introduction   -> /v7/introduction.md
 */
function toMarkdownPath(pathname: string): string {
  if (!pathname || pathname === '/') return '/index.md'
  const trimmed = pathname.replace(/\/+$/u, '')
  return `${trimmed}.md`
}

function resolveUrl(mdPath: string): string {
  if (typeof window === 'undefined') return mdPath
  return new URL(mdPath, window.location.origin).toString()
}

/**
 * RSPress-style "Copy Markdown" button with a dropdown of extra actions:
 *  - Copy Markdown
 *  - Copy Markdown link
 *  - Open in ChatGPT
 *  - Open in Claude
 *
 * Requires a matching /public mirror of the current route's page.md, which is
 * produced by scripts/generate-llms.mjs during prebuild.
 */
export function LlmsCopyButton() {
  const pathname = usePathname() || '/'
  const mdPath = toMarkdownPath(pathname)
  const [status, setStatus] = useState<Status>('idle')

  function flash(next: Status, revertAfterMs = 2000) {
    setStatus(next)
    if (next === 'copied' || next === 'error') {
      window.setTimeout(() => setStatus('idle'), revertAfterMs)
    }
  }

  async function copyMarkdown() {
    try {
      setStatus('copying')
      const response = await fetch(mdPath, { cache: 'no-store' })
      if (!response.ok) {
        throw new Error(`Unable to fetch ${mdPath} (${response.status})`)
      }
      const text = await response.text()
      await navigator.clipboard.writeText(text)
      flash('copied')
    } catch (error) {
      console.error('[LlmsCopyButton] copyMarkdown failed', error)
      flash('error')
    }
  }

  async function copyMarkdownLink() {
    try {
      setStatus('copying')
      await navigator.clipboard.writeText(resolveUrl(mdPath))
      flash('copied')
    } catch (error) {
      console.error('[LlmsCopyButton] copyMarkdownLink failed', error)
      flash('error')
    }
  }

  function openInLlm(service: 'chatgpt' | 'claude') {
    const pageUrl = resolveUrl(mdPath)
    const prompt =
      `Read ${pageUrl} and help me understand, summarize, and answer ` +
      `questions about the content.`
    const target =
      service === 'chatgpt'
        ? `https://chatgpt.com/?hints=search&q=${encodeURIComponent(prompt)}`
        : `https://claude.ai/new?q=${encodeURIComponent(prompt)}`
    window.open(target, '_blank', 'noopener,noreferrer')
  }

  const label =
    status === 'copying'
      ? 'Copying…'
      : status === 'copied'
        ? 'Copied!'
        : status === 'error'
          ? 'Copy failed'
          : 'Copy Markdown'

  return (
    <div className="not-prose mt-2 mb-8 inline-flex overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800/60">
      <button
        type="button"
        onClick={copyMarkdown}
        className={clsx(
          'flex items-center gap-2 px-3 py-1.5 text-sm font-medium transition-colors',
          'text-slate-700 hover:bg-slate-100 dark:text-slate-200 dark:hover:bg-slate-700/60',
          status === 'error' && 'text-rose-600 dark:text-rose-400',
          status === 'copied' && 'text-emerald-600 dark:text-emerald-400',
        )}
        aria-label={label}
      >
        <ClipboardIcon className="h-4 w-4" />
        <span>{label}</span>
      </button>
      <Menu as="div" className="relative flex">
        <MenuButton
          className={clsx(
            'flex items-center border-l border-slate-200 px-2 text-slate-500 transition-colors dark:border-slate-700 dark:text-slate-400',
            'hover:bg-slate-100 hover:text-slate-700 dark:hover:bg-slate-700/60 dark:hover:text-slate-200',
          )}
          aria-label="More copy options"
        >
          <ChevronDownIcon className="h-4 w-4" />
        </MenuButton>
        <MenuItems
          anchor="bottom end"
          className={clsx(
            'z-50 mt-1 w-64 overflow-hidden rounded-lg border border-slate-200 bg-white text-sm shadow-lg',
            'dark:border-slate-700 dark:bg-slate-800',
            'focus:outline-none',
          )}
        >
          <MenuItem>
            {({ focus }) => (
              <button
                type="button"
                onClick={copyMarkdown}
                className={clsx(
                  'flex w-full items-start gap-3 px-3 py-2 text-left',
                  focus
                    ? 'bg-slate-100 dark:bg-slate-700/60'
                    : 'bg-transparent',
                )}
              >
                <ClipboardIcon className="mt-0.5 h-4 w-4 text-slate-500 dark:text-slate-400" />
                <div>
                  <div className="font-medium text-slate-900 dark:text-white">
                    Copy Markdown
                  </div>
                  <div className="text-xs text-slate-500 dark:text-slate-400">
                    Copy this page as clean Markdown.
                  </div>
                </div>
              </button>
            )}
          </MenuItem>
          <MenuItem>
            {({ focus }) => (
              <button
                type="button"
                onClick={copyMarkdownLink}
                className={clsx(
                  'flex w-full items-start gap-3 px-3 py-2 text-left',
                  focus
                    ? 'bg-slate-100 dark:bg-slate-700/60'
                    : 'bg-transparent',
                )}
              >
                <LinkIcon className="mt-0.5 h-4 w-4 text-slate-500 dark:text-slate-400" />
                <div>
                  <div className="font-medium text-slate-900 dark:text-white">
                    Copy Markdown link
                  </div>
                  <div className="text-xs text-slate-500 dark:text-slate-400">
                    Copy the .md URL of this page.
                  </div>
                </div>
              </button>
            )}
          </MenuItem>
          <MenuItem>
            {({ focus }) => (
              <button
                type="button"
                onClick={() => openInLlm('chatgpt')}
                className={clsx(
                  'flex w-full items-start gap-3 px-3 py-2 text-left',
                  focus
                    ? 'bg-slate-100 dark:bg-slate-700/60'
                    : 'bg-transparent',
                )}
              >
                <ExternalLinkIcon className="mt-0.5 h-4 w-4 text-slate-500 dark:text-slate-400" />
                <div>
                  <div className="font-medium text-slate-900 dark:text-white">
                    Open in ChatGPT
                  </div>
                  <div className="text-xs text-slate-500 dark:text-slate-400">
                    Ask ChatGPT to read this page.
                  </div>
                </div>
              </button>
            )}
          </MenuItem>
          <MenuItem>
            {({ focus }) => (
              <button
                type="button"
                onClick={() => openInLlm('claude')}
                className={clsx(
                  'flex w-full items-start gap-3 px-3 py-2 text-left',
                  focus
                    ? 'bg-slate-100 dark:bg-slate-700/60'
                    : 'bg-transparent',
                )}
              >
                <ExternalLinkIcon className="mt-0.5 h-4 w-4 text-slate-500 dark:text-slate-400" />
                <div>
                  <div className="font-medium text-slate-900 dark:text-white">
                    Open in Claude
                  </div>
                  <div className="text-xs text-slate-500 dark:text-slate-400">
                    Ask Claude to read this page.
                  </div>
                </div>
              </button>
            )}
          </MenuItem>
        </MenuItems>
      </Menu>
    </div>
  )
}

function ClipboardIcon(props: React.ComponentPropsWithoutRef<'svg'>) {
  return (
    <svg
      viewBox="0 0 20 20"
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <rect x="5" y="3" width="10" height="14" rx="2" />
      <path d="M8 3h4a1 1 0 0 1 1 1v1H7V4a1 1 0 0 1 1-1Z" />
    </svg>
  )
}

function ChevronDownIcon(props: React.ComponentPropsWithoutRef<'svg'>) {
  return (
    <svg
      viewBox="0 0 20 20"
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="m6 8 4 4 4-4" />
    </svg>
  )
}

function LinkIcon(props: React.ComponentPropsWithoutRef<'svg'>) {
  return (
    <svg
      viewBox="0 0 20 20"
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M8.5 11.5a3.5 3.5 0 0 0 4.95 0l3-3a3.5 3.5 0 0 0-4.95-4.95l-1 1" />
      <path d="M11.5 8.5a3.5 3.5 0 0 0-4.95 0l-3 3a3.5 3.5 0 0 0 4.95 4.95l1-1" />
    </svg>
  )
}

function ExternalLinkIcon(props: React.ComponentPropsWithoutRef<'svg'>) {
  return (
    <svg
      viewBox="0 0 20 20"
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M12 4h4v4" />
      <path d="m9 11 7-7" />
      <path d="M15 12v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h3" />
    </svg>
  )
}
